{
	"version": 1699520519,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite-sheet0.png",
		"images/bomb-sheet0.png",
		"images/bomb-sheet1.png",
		"images/bomb-sheet2.png",
		"images/ballon-sheet0.png",
		"images/missile-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/street-sheet0.png",
		"images/tiledbackground.png",
		"images/particles2.png",
		"images/menu-sheet0.png",
		"images/easy-sheet0.png",
		"images/play-sheet0.png",
		"images/hard-sheet0.png",
		"images/audiobutton-sheet0.png",
		"images/audiobutton-sheet1.png",
		"images/sprit-sheet0.png",
		"images/bhome-sheet0.png",
		"images/bhome-sheet1.png",
		"images/home_bt-sheet0.png",
		"images/playpause_bt-sheet0.png",
		"images/playpause_bt-sheet1.png",
		"media/bump2.m4a",
		"media/bump2.ogg",
		"media/explosion 5.m4a",
		"media/explosion 5.ogg",
		"media/epicarpg.m4a",
		"media/epicarpg.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}